### ISSUE TITLE
Undefined method 'join' for NilClass

### ISSUE THREAD

**Issue by rbellido54** [nevinera/quiet_quality#103]
The new 1.3.0 version results in the following error after running our CI command:
```
❯ bundle exec qq \
    rubocop standardrb haml_lint \
    --annotate-github-stdout \
    --executor concurrent \
    --changed-files \
    --filter-messages \
    --comparison-branch=origin/master \
    --no-config
```
```
#<Thread:0x000000010d5fcd60 /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/concurrent_executor.rb:13 run> terminated with exception (report_on_exception is true):
#<Thread:0x000000010d5fcb08 /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/concurrent_executor.rb:13 run> terminated with exception (report_on_exception is true):
#<Thread:0x000000010d5fc770 /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/concurrent_executor.rb:13 run> terminated with exception (report_on_exception is true):
/Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/pipeline.rb:57:in `log_runner': undefined method `join' for nil:NilClass (NoMethodError)

        info("Runner #{r.tool_name} command: `#{r.command.join(" ")}`")
                                                         ^^^^^
        from /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/pipeline.rb:53:in `block in runner'
        from <internal:kernel>:90:in `tap'
        from /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/pipeline.rb:53:in `runner'
        from /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/pipeline.rb:38:in `runner_outcome'
        from /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/pipeline.rb:17:in `outcome'
        from /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/concurrent_executor.rb:14:in `block in threaded_pipeline'
/Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/pipeline.rb:57:in `log_runner': undefined method `join' for nil:NilClass (NoMethodError)

        info("Runner #{r.tool_name} command: `#{r.command.join(" ")}`")
                                                         ^^^^^
        from /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/pipeline.rb:53:in `block in runner'
        from <internal:kernel>:90:in `tap'
        from /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/pipeline.rb:53:in `runner'
        from /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/pipeline.rb:38:in `runner_outcome'
        from /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/pipeline.rb:17:in `outcome'
        from /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/concurrent_executor.rb:14:in `block in threaded_pipeline'
/Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/pipeline.rb:57:in `log_runner': undefined method `join' for nil:NilClass (NoMethodError)

        info("Runner #{r.tool_name} command: `#{r.command.join(" ")}`")
                                                         ^^^^^
        from /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/pipeline.rb:53:in `block in runner'
        from <internal:kernel>:90:in `tap'
        from /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/pipeline.rb:53:in `runner'
        from /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/pipeline.rb:38:in `runner_outcome'
        from /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/pipeline.rb:17:in `outcome'
        from /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/concurrent_executor.rb:14:in `block in threaded_pipeline'
bundler: failed to load command: qq (/Users/rbellido/.rbenv/versions/3.1.2/bin/qq)
/Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/pipeline.rb:57:in `log_runner': undefined method `join' for nil:NilClass (NoMethodError)

        info("Runner #{r.tool_name} command: `#{r.command.join(" ")}`")
                                                         ^^^^^
        from /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/pipeline.rb:53:in `block in runner'
        from <internal:kernel>:90:in `tap'
        from /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/pipeline.rb:53:in `runner'
        from /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/pipeline.rb:38:in `runner_outcome'
        from /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/pipeline.rb:17:in `outcome'
        from /Users/rbellido/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/quiet_quality-1.3.0/lib/quiet_quality/executors/concurrent_executor.rb:14:in `block in threaded_pipeline'
```

Rolling back to the previous version, 1.2.2, and this error is not shown. No changes on the `quiet_quality.yml` file. All that's done here is doing `bundle update --conservative quiet_quality` and running the same `qq` command right after.

**Comment by nevinera** [comment]
Hmm. A `nil` command should mean that `skip_execution?` is evaluating as `true` for that runner - that probably means a presentational situation I'm not currently testing in conjunction with a skippable runner. I'll get this sorted this evening, sorry about that!
